config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'reports/report_by_category'
  get 'reports/report_by_dates'
  root 'main#index'
  get 'main/index'
  resources :operations
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :operations
  paginates_per 5

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, uniqueness: true, allow_nil: false
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :category
  paginates_per 5

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :odate, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.page(params[:page])
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]

  # GET /operations or /operations.json
  def index
    @operations = Operation.page(params[:page])
  end

  # GET /operations/1 or /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations or /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully created." }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1 or /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to operation_url(@operation), notice: "Operation was successfully updated." }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1 or /operations/1.json
  def destroy
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url, notice: "Operation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_operation
    @operation = Operation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def operation_params
    params.require(:operation).permit(:amount, :odate, :description, :category_id)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def report_by_category
    @start_date = params[:start_date]
    @end_date = params[:end_date]

    category_data = Operation.where("odate BETWEEN ? AND ?", @start_date, @end_date).group("category_id").sum(:amount)

    category_data = category_data.map { |i, amount| [Category.find(i).name, amount] }

    @category_name = category_data.map { |m| m[0] }
    @category_amount = category_data.map { |m| m[1] }
  end

  def report_by_dates
    @start_date = params[:start_date]
    @end_date = params[:end_date]

    dates_data = Operation.where("odate BETWEEN ? AND ?", @start_date, @end_date).group("odate").sum(:amount)

    dates_data = dates_data.map { |date, amount| [date.strftime("%Y-%m-%d %H:%M %Z"), amount] }

    @date = dates_data.map { |m| m[0] }
    @date_amount = dates_data.map { |m| m[1] }
    puts(@date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/categories/_category.html.erb
<div class="category_page">
  <div id="<%= dom_id category %>">
    <tr>
      <div>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td class="text-center">
          <%= link_to "Show", category_path(category), class: 'btn btn-info' %>
          <%= link_to "Edit", edit_category_path(category), class: 'btn btn-success' %>
          <%= button_to "Delete", category , data: {confirm: 'Are you sure?'}, method: :delete, class:"btn btn-danger" %>
        </div>
      </tr>
    </div>
  </div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
    <div class="form-group">
      <div class="col-md-6">
        <%= form.label :title %><br>
        <%= form.text_field :name, class: 'form-control' %>
        <br>
        <%= form.label :body %>
        <%= form.text_area :description, class: 'form-control' %>
        <br>
        <div class='form_category_sumbit'>
          <%= form.submit class: 'btn btn-success'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class='category_edit'>
  <h1>Editing category</h1>
</div>
<%= render "shared/form", category: @category %>
<br>
<div class="btn-group" role="group">
  <%= link_to "Show this category", @category, class:'btn btn-info' %>
  <%= link_to "Back to categories", categories_path ,class:'btn btn-warning'%>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "New category", new_category_path, class:"btn btn-primary" %>
<div class="container">
  <div class="page-header">
    <h1>Category</h1>
  </div>
</div>
<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Name of Category</th>
        <th>Description</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <%= render category %>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @categories %>

app/views/categories/new.html.erb
<h1 class='new_category'>New category</h1>
<%= render "form", category: @category %>
<br>
<div class='back_to_categories'>
  <%= link_to "Back to categories", categories_path, class:'btn btn-info' %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render "shared/category" %>
<div class="showbtn">
  <%= link_to "Edit this category", edit_category_path(@category),class:"btn btn-info" %>
  <%= link_to "Back to categories", categories_path, class:"btn btn-success" %>
  <%= button_to "Destroy this category", @category, method: :delete, class:"btn btn-danger" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: 'shared/menu' %>
    <%= yield %>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/main/index.html.erb
<div class="container">
  <div class="application">
    <h1>Finance Manager Application</h1>
  </div>
  <div class="app_info">
    <div>
      <%= link_to "Category", categories_path, class:"btn btn-info" %>
    </div>
    <br>
    <div>
      <%= link_to "Operation", operations_path, class:"btn btn-success" %>
    </div>
    <br>
    <div>
      <%= link_to "Reports", reports_index_path, class:"btn btn-warning" %>
    </div>
  </div>
</div>

app/views/operations/_form.html.erb
<%= form_with(model: operation) do |form| %>
  <% if operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>
      <ul>
        <% operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="op_amount">
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>
  <div class="op_odate">
    <%= form.label :odate, style: "display: block" %>
    <%= form.datetime_field :odate %>
  </div>
  <div class="op_description">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>
  <div class="op_category">
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>
  <div class="op_submit">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/operations/_operation.html.erb
<div id="<%= dom_id operation %>">
  <div class="clear-block">
    <p>
      <strong>Amount:</strong>
      <%= operation.amount %>
    </p>
    <p>
      <strong>Odate:</strong>
      <%= operation.odate %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= operation.description %>
    </p>
    <p>
      <strong>Category:</strong>
      <%= [operation.category_id] %>
      <%= Category.find(operation.category_id).name %>
    </p>
  </div>
</div>

app/views/operations/edit.html.erb
<div class="edit_operation">
  <h1>Editing operation</h1>
</div>
<%= render "form", operation: @operation %>
<br>
<div class="op_links">
  <%= link_to "Show this operation", @operation, class:"btn btn-info" %>
  <%= link_to "Back to operations", operations_path, class:"btn btn-warning" %>
</div>

app/views/operations/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="new_operation">
  <%= link_to "New operation", new_operation_path, class:"btn btn-success" %>
</div>
<div class="operations">
  <h1>Operations</h1>
</div>
<div id="operations">
  <% @operations.each do |operation| %>
    <%= render operation %>
    <p>
      <div class="show_operations">
        <%= link_to "Show this operation", operation, class:"btn btn-info" %>
      </div>
    </p>
    <hr>
  <% end %>
</div>
<%= paginate @operations %>

app/views/operations/new.html.erb
<div class="new_op">
  <h1>New operation</h1>
</div>
<%= render "form", operation: @operation %>
<br>
<div id="back_operation">
  <%= link_to "Back to operations", operations_path, class:"btn btn-warning" %>
</div>

app/views/operations/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @operation %>
<div class="show_operations">
  <%= link_to "Edit this operation", edit_operation_path(@operation), class:"btn btn-info" %>
  <%= link_to "Back to operations", operations_path, class:"btn btn-warning" %>
  <%= button_to "Destroy this operation", @operation, method: :delete, class:"btn btn-danger" %>
</div>

app/views/reports/_helper.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script type='text/javascript'>
  (function(){
    if(!sessionStorage.getItem('firstLoad')){
      sessionStorage['firstLoad'] = true;
      window.location.reload();
    }else{
      sessionStorage.removeItem('firstLoad');
    }})();
</script> 

app/views/reports/index.html.erb
<div class="container">
  <%= render "helper" %>
  <div class="report_generator">
    <h1>Reports Generator</h1>
  </div>
  <%= form_with url: "report_by_category", method: :get do |form| %>
    <div class=reports>
      <div>
        <%= form.label 'Type of Operation' %><br>
        <%= form.select :type_operation, ["Spending", "Income"] %>
      </div>
      <br>
      <div>
        <%= form.label 'Category' %><br>
        <%= form.select :category_id, Category.pluck(:name,:id) %>
      </div>
      <br>
      <div>
        <%= form.label 'From' %><br>
        <%= form.datetime_field :start_date %>
      </div>
      <br>
      <div>
        <%= form.label 'To' %><br>
        <%= form.datetime_field :end_date %>
      </div>
      <br>
      <%= link_to "Home", root_path, class:"btn btn-outline-dark", class:"btn btn-warning" %>
      <%= form.submit "Report by Category", class:"btn btn-success" %>
      <input type="reset" value="Clear" class="btn btn-danger">
      <input type="submit" formaction='report_by_dates' value="Report by Dates" class="btn btn-info">
    <% end %>
    <br>
  </div>
</div>

app/views/reports/report_by_category.html.erb
<div class="container">
  <div class="report_c">
    <h1>Report by Category</h1>
    <div class="chart-container" style="position: relative; height:60vh; width:160vw">
      <canvas id="report_by_category"></canvas>
    </div>
  </div>
  <script>
    const ctx = document.getElementById('report_by_category');
    const data = {
    labels: <%= raw @category_name %>,
    datasets: [{
      label: 'Report by Category',
      data: <%= raw @category_amount %>,
      backgroundColor: [
        'rgb(255, 99, 132)',
        'rgb(54, 162, 235)',
        'rgb(255, 205, 86)',
        'rgb(243, 105, 36)',
        'rgb(0, 158, 73)',
        'rgb(0, 188, 242)',
        'rgb(186, 216, 10)',
        'rgb(255, 241, 0)',
        'rgb(236, 0, 140)',
        'rgb(0, 178, 148)'
      ],
      hoverOffset: 4
    }]
    };
    const config = {
    type: 'doughnut',
    data: data,
    responsive: true,
    options: {
          plugins: {
              title: {
                  display: true,
                  text: 'Report from '+['<%= @start_date %>']+ ' to ' +
                  ['<%= @end_date %>']
              }
          }
      }
    };

    const report_by_category = new Chart(ctx,config);
  </script>
</div>

app/views/reports/report_by_dates.html.erb
<div class="container">
  <div class="report_d">
    <h1>Reports by Dates</h1>
    <canvas id='report_by_dates' width='900' height='400'></canvas>
  </div>
  <script>
    const ctx = document.getElementById('report_by_dates');
    const data = {
    labels: <%= raw @date %>,
    datasets: [{
      label: 'Report by Dates',
      data: <%= raw @date_amount %>,
      fill: false,
      borderColor: 'rgb(75, 192, 192)',
      tension: 0.1
    }]
    };

    const config = {
    type: 'line',
    data: data,
    options:{
      responsive:false,
      plugins: {
              title: {
                  display: true,
                  text: 'Report from '+['<%= @start_date %>']+ ' to ' +
                  ['<%= @end_date %>']
              }
          }
    }
    };
    const report_by_category = new Chart(ctx,config);
  </script>
</div>

app/views/shared/_category.html.erb
<div id="<%= dom_id @category %>">
  <div id="category">
    <h1>Category Id : <span class="label label-default"></span>
      <%= @category.id %>
    </h1>
  </div>
  <div id="label">
    <h4>Name: <span class="label label-default"></span>
    </h4>
    <%= @category.name %>
    <h4>Category description: <span class="label label-default"></span>
    </h4>
    <%= @category.description %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-center text-white">
  <div class="container p-4 pb-0 md">
    <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/in/serhii-shtelmakh-9a0264b0/" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
    <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/SerhiiSt/finance_app" role="button"
        ><i class="fab fa-github"></i
      ></a>
  </section>
</div>
<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
  © 2023 Copyright:
  <a class="text-white" href="https://www.linkedin.com/in/serhii-shtelmakh-9a0264b0/">Serhii Shtelmakh</a>
</div>
</footer>

app/views/shared/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class='row'>
    <div class="form-group">
      <div class="col-md-6">
        <%= f.label :title %><br>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        <%= f.label :body %>
        <%= f.text_area :description, class: 'form-control' %>
        <br>
        <div>
          <%= f.submit class: 'btn btn-success'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Finance Manager Application</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/categories">Category</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/operations">Operation</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/reports/index">Reports</a>
        </li>
      </ul>
    </div>
  </div>
</nav>